Feature/create default plan configuration
qualabs/video-headline pull request #17
Opened 2023-11-24 14:22 UTC by Franco0712

## Description:
Add a default Plan for the organizations, it gets the default plan and its configuration from the one created in the migrations.
Blank=True is not set so the user cannot choose the "None" plan option.
This PR should be merged after the create-default-configuration PR because it creates the default plans in the migrations that will be used here
## Screenshots (if appropriate):
![image](https://github.com/qualabs/video-headline/assets/146981379/d320ba45-70a4-450d-a0d6-047584430fc7)

2023-11-24 16:37 UTC, fyoungqualabs requested changes

2023-11-24 16:37 UTC, fyoungqualabs commented on organization/models/organization.py
> +    print('Instance')
is this log necessary?

2023-11-24 16:41 UTC, fyoungqualabs approved these changes

2023-11-29 17:40 UTC, NoeliaBentancor commented on organization/models/organization.py
> +    if (
Why are we changing this?

2023-11-29 17:42 UTC, NoeliaBentancor commented on CONTRIBUTING.md
> -# Video Headline - Contributing
Why are we deleting this?

2023-12-04 19:37 UTC, fyoungqualabs approved these changes
I re-tested the changes and everything works fine!

2023-12-05 13:27 UTC, capuajuan approved these changes
All good

2023-12-05 13:55 UTC, merged